project:
  type: website
  output-dir: docs

website:
  title: "Tan spot SAD"
  navbar:
    left:
      - href: index.qmd
        text: "<i class='bi bi-book-half'></i> About"
      - href: about.qmd
        text: "<i class='bi bi-bar-chart-fill'></i> Analysis"
    right:
      - href: hhttps://github.com/tomazrg/paper-SAD_tan_spot_wheat
        text: "<i class='bi bi-github'></i> GitHub"
      - href: https://www.linkedin.com/in/ricardo-gomes-tom%C3%A1z-0137ba189/
        text: "<i class='bi bi-linkedin'></i> Linkedin"

format:
  html:
    theme: flatly
    css: styles.css
    df-print: paged
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    lib_dir: site_libs
    self_contained: true